### ISSUE TITLE
naive-go seems to have some issues that I can't resolve at the moment

### ISSUE THREAD

**Issue by lls275** [klzgrad/naiveproxy#293]
naive-go https://github.com/SagerNet/cronet-go seems to have some issues that I can't resolve at the moment. I tried compiling and it was successful, but couldn't connect. Both my run and compile platforms are on linux64

```
root@q:~/cronet-go# ./naive-go 
Usage:
  naive-go [flags]

Flags:
      --enable-redir                 enable redir support (linux only)
      --extra-headers string         extra headers split by CRLF
  -h, --help                         help for naive-go
      --host-resolver-rules string   resolver rules
      --insecure-concurrency= int    use N connections, insecure (default 1)
      --listen string                <addr:port> set listen address
      --log string                   log to stderr, or file (default disabled) (default "disabled")
      --proxy string                 <proto>://[<user>:<pass>@]<hostname>[:<port>] proto: https, quic
  -v, --version                      version for naive-go
FATA[0000] [naive]: missing listen address              
root@q:~/cronet-go# ./naive-go --proxy https://user:pass@www.example.com:443 --listen 0.0.0.0:1080
INFO[0000] [naive]: mixed client started at 0.0.0.0:1080 
INFO[0016] [naive]: 127.0.0.1:48486 => 104.200.28.42:443 
INFO[0026] [naive]: 127.0.0.1:48502 => 104.200.28.42:443 
INFO[0028] [naive]: 127.0.0.1:48504 => 104.200.28.42:443 
WARN[0260] [naive]: read http request: malformed HTTP request "\x00" 
INFO[0265] [naive]: 127.0.0.1:48774 => ip.gs:443        
WARN[0278] [naive]: read http request: malformed HTTP request "\x00" 
WARN[0359] [naive]: read http request: malformed HTTP request "\x00" 
WARN[0365] [naive]: read http request: malformed HTTP request "\x00" 
INFO[0380] [naive]: 127.0.0.1:48894 => 104.193.88.77:443 
INFO[0395] [naive]: 127.0.0.1:48912 => www.baidu.com:443 
INFO[0421] [naive]: 127.0.0.1:48942 => 104.193.88.77:443 
INFO[0439] [naive]: 127.0.0.1:48960 => 14.215.177.38:443 
panic: runtime error: index out of range [3] with length 3

goroutine 49 [running]:
main.(*PaddingConn).WriteBuffer(0xc000130ab0, 0xc0001cfda0)
        /root/cronet-go/naive/main.go:342 +0x185
github.com/sagernet/sing/common/bufio.CopyExtended({0x7f290d86b230?, 0xc000130ab0}, {0x56367cb4e7a0?, 0xc0000597d0?})
        /root/go/pkg/mod/github.com/sagernet/sing@v0.0.0-20220522025344-b21aa294fca3/common/bufio/conn.go:85 +0x332
github.com/sagernet/sing/common/bufio.Copy({0x7f290d86b1a8, 0xc000130ab0}, {0x56367cb4d200?, 0xc000010118})
        /root/go/pkg/mod/github.com/sagernet/sing@v0.0.0-20220522025344-b21aa294fca3/common/bufio/conn.go:64 +0x274
github.com/sagernet/sing/common/bufio.CopyConn.func1()
        /root/go/pkg/mod/github.com/sagernet/sing@v0.0.0-20220522025344-b21aa294fca3/common/bufio/conn.go:97 +0x125
github.com/sagernet/sing/common/task.Run.func1()
        /root/go/pkg/mod/github.com/sagernet/sing@v0.0.0-20220522025344-b21aa294fca3/common/task/task.go:28 +0x45
created by github.com/sagernet/sing/common/task.Run
        /root/go/pkg/mod/github.com/sagernet/sing@v0.0.0-20220522025344-b21aa294fca3/common/task/task.go:27 +0xd7
root@q:~/cronet-go# 
root@q:~/cronet-go# 
root@q:~/cronet-go# 
```
I tried to use socks5 to connect, but it reported this error
```
curl --socks5 127.0.0.1:1080 https://ip.gs
```
socks5 error:
```
panic: runtime error: index out of range [3] with length 3

goroutine 49 [running]:
main.(*PaddingConn).WriteBuffer(0xc000130ab0, 0xc0001cfda0)
        /root/cronet-go/naive/main.go:342 +0x185
github.com/sagernet/sing/common/bufio.CopyExtended({0x7f290d86b230?, 0xc000130ab0}, {0x56367cb4e7a0?, 0xc0000597d0?})
        /root/go/pkg/mod/github.com/sagernet/sing@v0.0.0-20220522025344-b21aa294fca3/common/bufio/conn.go:85 +0x332
github.com/sagernet/sing/common/bufio.Copy({0x7f290d86b1a8, 0xc000130ab0}, {0x56367cb4d200?, 0xc000010118})
        /root/go/pkg/mod/github.com/sagernet/sing@v0.0.0-20220522025344-b21aa294fca3/common/bufio/conn.go:64 +0x274
github.com/sagernet/sing/common/bufio.CopyConn.func1()
        /root/go/pkg/mod/github.com/sagernet/sing@v0.0.0-20220522025344-b21aa294fca3/common/bufio/conn.go:97 +0x125
github.com/sagernet/sing/common/task.Run.func1()
        /root/go/pkg/mod/github.com/sagernet/sing@v0.0.0-20220522025344-b21aa294fca3/common/task/task.go:28 +0x45
created by github.com/sagernet/sing/common/task.Run
        /root/go/pkg/mod/github.com/sagernet/sing@v0.0.0-20220522025344-b21aa294fca3/common/task/task.go:27 +0xd
```

If I use socks4 to proxy, I get this error
```
curl --socks4 127.0.0.1:1080 https://ip.gs
```
```
[0615/113207.808816:ERROR:cert_verify_proc_builtin.cc(603)] No net_fetcher for performing AIA chasing.
```

**Comment by Johnshall** [comment]
You should hide your ip right now.

**Comment by klzgrad** [comment]
Raise the issue with https://github.com/SagerNet/cronet-go and strip your logs of personal identifying information. Note that your comment will always be visible through Github api, so this time I can only do some cosmetic save for you, i.e. deleting this.
